server:
  port: 8425
  compression: # 开启压缩
    enabled: true
    min-response-size: 2048
    mime-types:
      - text/html
      - text/xml
      - text/plain
      - text/css
      - text/javascript
      - application/javascript
      - application/json

management: # 开启监控
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    cn.yifan.geekgen.mapper : debug

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 604800
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # token前缀
  token-prefix: Bearer

mysql:
  driver-class-name: com.mysql.cj.jdbc.Driver
  host: 117.72.46.175
  port: 3268
  database: geekgen
  username: root
  password: cyf829CMT917

spring:
  application:
    name: geekgen-java
  datasource:
    druid:
      driver-class-name: ${mysql.driver-class-name}
      url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${mysql.username}
      password: ${mysql.password}
  rabbitmq:
    host: 117.72.46.175
    port: 5678
    username: geekgen
    password: geekgen
    virtual-host: /geekgen
    models:
      - exchange:
          name: direct_task_processing_exchange_1
        queues:
          - name: direct_task_processing_exchange_1_queue_1
            routing-key: task_1
          - name: direct_task_processing_exchange_1_queue_2
            routing-key: task_2
  data:
    redis:
      host: 117.72.9.87
      port: 6278
      database: 5
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
    mongodb:
      host: 117.72.46.175
      port: 26084
      database: geekgen

mybatis:
  #mapper配置文件
  mapper-locations: classpath*:mapper/*.xml # classpath*: 会搜索所有类路径（包括依赖 jar 包中的资源）
  type-aliases-package: cn.yifan.geekgen.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

langchain4j:
  open-ai:
    chat-model:
      base-url: https://ark.cn-beijing.volces.com/api/v3
      api-key: 38e2b6ed-2af3-440d-a28b-2f3b1c4aaafc
      model-name: ep-20250129233540-8rztb
      log-requests: true
      log-responses: true
      #response-format: json_schema
      #strict-json-schema: true
    streaming-chat-model:
      base-url: https://ark.cn-beijing.volces.com/api/v3
      api-key: 38e2b6ed-2af3-440d-a28b-2f3b1c4aaafc
      model-name: ep-20250129233540-8rztb
      log-requests: true
      log-responses: true
